image: jojomi/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - HUGO_ENV=production hugo --gc --minify && gzip -k -6 $(find public -type f)
  artifacts:
    paths:
    - public
  only:
  - master
