baseUrl: https://tckb.tgrthi.me/
title: "tscha-n-dra-s"
theme: hugo-vitae
languagecode: en
defaultcontentlanguage: en
paginate: 5
canonifyurls: true
pygmentsstyle: bw
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
disqusShortname: tckb
enableEmoji: true
enableRobotsTXT: true
enableGitInfo: true
footnoteReturnLinkContents: ↩
googleAnalytics: "UA-167549458-1"
uglyURLs: false
copyright: "© 2020 Copyright notice | [Vitae](https://github.com/dataCobra/hugo-vitae) theme for [Hugo](https://gohugo.io)"

taxonomies:
  category: categories
  series: series
  tag: tags

frontmatter:
  date:
    - date
    - ":git"
    - default

Permalinks:
  posts: "/:year/:filename/"

menu:
  main:
    - name: Me
      url: /about/
      weight: 3
    - name: Blog Posts
      url: /posts/
      weight: 1
    - name: Tags
      url: /tags/
      weight: 2

minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: false
  tdewolff:
    css:
      decimals: -1
      keepCSS2: true
    html:
      keepConditionalComments: true
      keepDefaultAttrVals: true
      keepDocumentTags: true
      keepEndTags: true
      keepWhitespace: false
    js: {}
    json: {}
    svg:
      decimals: -1
    xml:
      keepWhitespace: false

author:
  name: Chandra
privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    disable: true
    useSessionStorage: false
  twitter:
    disable: false
    enableDNT: true
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

params:
  mainSections:
    - posts
  keywords:
    - devops
    - kubernetes
  avatar: "/img/profile.jpg"
  since: 2020
  pagetitle: "All things about DevOps++"
  subtitle: "All things about DevOps++"
  socialShare: true
  commit: "https://gitlab.com/tckb1/tckb1.gitlab.io/tree/"
  favicon_png: favicon.png
  favicon_png_sizes: 16x16 32x32
  appleicon: apple-touch-icon.png
  license: 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  listAuthor: true
  social:
    - name: Github
      icon: fab fa-github
      url: "https://github.com/tckb"
    - name: Linkedin
      icon: fab fa-linkedin
      url: "https://linkedin.com/in/chandrakiranbt"
    - name: Twitter
      icon: fab fa-twitter
      url: "https://twitter.com/this_is_tckb"
    - name: Gitlab
      icon: fab fa-gitlab
      url: "https://gitlab.com/tckb1"
    - name: RSS
      icon: fas fa-rss
      url: /index.xml
  share:
    Twitter: true
    Facebook: false
    Linkedin: true
    HackerNews: true
    copyright: "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    publisher:
      name: Chandra
      logo:
        url: logo.png
        width: 127
        height: 40
    logo:
      url: profile.jpg
      width: 127
      height: 40
    image:
      url: profile.jpg
      width: 800
      height: 600
